# Generated by Django 5.0.3 on 2024-09-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_mail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_portal.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news_portal.PostCategory', to='news_portal.category', verbose_name='Категория публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postType',
            field=models.CharField(choices=[('NS', 'Новости'), ('AL', 'Статья')], default='NS', max_length=2, verbose_name='Тип публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок поста'),
        ),
    ]
